version: "3.8"
services:
    #Base de données
    database:
        image: mysql
        container_name: database_docker_common
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    #phpmyAdmin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_h3
        restart: always
        depends_on:
            - database
        ports:
            - 1515:80
        environment:
            PMA_HOST: database
        networks:
            - dev  
    #maildev        
    maildev:
        image: maildev/maildev
        container_name: maildev_docker_h3
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "1516:80"
        restart: always
        networks:
            - dev 
    #apache php
    www:
        build: php
        container_name: www_docker_h3
        ports:
          - "1010:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
networks:
    dev:

volumes:
    db-data: